## Base image for all the stages
FROM node:20-alpine AS base

ARG USE_NPM_CN_MIRROR

ENV PNPM_HOME="/pnpm" \
    PATH="$PNPM_HOME:$PATH"

RUN \
    # If you want to build docker in China, build with --build-arg USE_NPM_CN_MIRROR=true
    if [ "${USE_NPM_CN_MIRROR:-false}" = "true" ]; then \
        npm config set registry "https://registry.npmmirror.com/"; \
    fi \
    # Add user nextjs to run the app
    && addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

## Sharp dependencies, copy all the files for production
FROM base AS sharp

WORKDIR /app

RUN corepack enable \
    && pnpm add sharp

## Install dependencies only when needed
FROM base AS builder

WORKDIR /app

ENV NEXT_PUBLIC_BASE_PATH="" \
    NEXT_PUBLIC_SERVICE_MODE=server \
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuMzM3OTI0Lnh5eiQ \
    NEXT_PUBLIC_S3_DOMAIN=https://lobechat.337924.xyz/lobechat \
    KEY_VAULTS_SECRET=jgwsK58dspyVQoIf8/M3IIHl1h8LYYce3YNXeLpy6uk= \
    DATABASE_URL=postgres://lobechat:yrFAbDhSTdMNZ2A2@192.168.0.101:5432/lobechat \
    CLERK_WEBHOOK_SECRET=whsec_jPOfPvrlmDmSQmAP1e/ebKuyi/MBlKrb \
    DATABASE_DRIVER=node

# Node
ENV NODE_OPTIONS="--max-old-space-size=8192"

COPY package.json ./
COPY .npmrc ./

RUN corepack enable \
    && pnpm i

COPY . .

# run build standalone for docker version
RUN npm run build:docker

## Application image, copy all the files for production
FROM scratch AS app

COPY --from=builder /app/public /app/public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder /app/.next/standalone /app/
COPY --from=builder /app/.next/static /app/.next/static
COPY --from=sharp /app/node_modules/.pnpm /app/node_modules/.pnpm

## Production image, copy all the files and run next
FROM base

# Copy all the files from app, set the correct permission for prerender cache
COPY --from=app --chown=nextjs:nodejs /app /app

ENV NODE_ENV="production"

# set hostname to localhost
ENV HOSTNAME="0.0.0.0" \
    PORT="3210"

# General Variables
ENV ACCESS_CODE="" \
    NEXT_PUBLIC_SERVICE_MODE=server \
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuMzM3OTI0Lnh5eiQ \
    NEXT_PUBLIC_S3_DOMAIN=https://lobechat.337924.xyz/lobechat \
    KEY_VAULTS_SECRET=jgwsK58dspyVQoIf8/M3IIHl1h8LYYce3YNXeLpy6uk= \
    DATABASE_URL=postgres://lobechat:yrFAbDhSTdMNZ2A2@192.168.0.101:5432/lobechat \
    CLERK_WEBHOOK_SECRET=whsec_jPOfPvrlmDmSQmAP1e/ebKuyi/MBlKrb \
    DATABASE_DRIVER=node \
    API_KEY_SELECT_MODE=""

# Model Variables
ENV \
    # OpenAI
    OPENAI_API_KEY="" OPENAI_MODEL_LIST="" OPENAI_PROXY_URL="" \

USER nextjs

EXPOSE 3210/tcp

CMD ["node", "/app/server.js"]
