FROM node:20-slim AS base

## Sharp dependencies, copy all the files for production
FROM base AS sharp
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

RUN pnpm add sharp

## Install dependencies only when needed
FROM base AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json ./
COPY .npmrc ./

# If you want to build docker in China
# RUN npm config set registry https://registry.npmmirror.com/
RUN pnpm i

COPY . .

ENV NEXT_PUBLIC_BASE_PATH=""
ENV NEXT_PUBLIC_SERVICE_MODE=server
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuMzM3OTI0Lnh5eiQ
ENV NEXT_PUBLIC_S3_DOMAIN=https://lobechat.337924.xyz/lobechat
ENV KEY_VAULTS_SECRET=jgwsK58dspyVQoIf8/M3IIHl1h8LYYce3YNXeLpy6uk=
ENV DATABASE_URL=postgres://lobechat:yrFAbDhSTdMNZ2A2@192.168.0.101:5432/lobechat
ENV CLERK_WEBHOOK_SECRET=whsec_jPOfPvrlmDmSQmAP1e/ebKuyi/MBlKrb
ENV DATABASE_DRIVER=node

# Node
ENV NODE_OPTIONS "--max-old-space-size=8192"

# run build standalone for docker version
RUN npm run build:docker

## Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=sharp --chown=nextjs:nodejs /app/node_modules/.pnpm ./node_modules/.pnpm

USER nextjs

EXPOSE 3210

# set hostname to localhost
ENV HOSTNAME="0.0.0.0"
ENV PORT=3210

# General Variables
ENV ACCESS_CODE=""
ENV NEXT_PUBLIC_SERVICE_MODE=server
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuMzM3OTI0Lnh5eiQ
ENV NEXT_PUBLIC_S3_DOMAIN=https://lobechat.337924.xyz/lobechat
ENV KEY_VAULTS_SECRET=jgwsK58dspyVQoIf8/M3IIHl1h8LYYce3YNXeLpy6uk=
ENV DATABASE_URL=postgres://lobechat:yrFAbDhSTdMNZ2A2@192.168.0.101:5432/lobechat
ENV CLERK_WEBHOOK_SECRET=whsec_jPOfPvrlmDmSQmAP1e/ebKuyi/MBlKrb
ENV DATABASE_DRIVER=node
ENV API_KEY_SELECT_MODE=""

# OpenAI
ENV OPENAI_API_KEY=""
ENV OPENAI_PROXY_URL=""
ENV OPENAI_MODEL_LIST=""

CMD ["node", "server.js"]
